DoAnChuyenNganh_HeThongTrungTamTinHoc/Areas/Admin/Controllers/AdminTinTucThongBaoController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DoAnChuyenNganh_HeThongTrungTamTinHoc.Models;

namespace DoAnChuyenNganh_HeThongTrungTamTinHoc.Areas.Admin.Controllers
{
    public class AdminTinTucThongBaoController : Controller
    {
        TrungTamTinHocEntities db = new TrungTamTinHocEntities();
        // GET: Admin/AdminTinTucThongBao
        public ActionResult DanhSachTinTucThongBao(string search = "", string sortOrder = "tieude", int page = 1, int pageSize = 10)
        {
            var tintucthongbaoQuery = db.TinTucThongBao.AsQueryable();

            if (!string.IsNullOrEmpty(search))
            {
                tintucthongbaoQuery = tintucthongbaoQuery.Where(tt => tt.TieuDe.Contains(search));
            }

            switch (sortOrder)
            {
                case "tieude":
                    tintucthongbaoQuery = tintucthongbaoQuery.OrderBy(tt => tt.TieuDe);
                    break;
                case "noidung":
                    tintucthongbaoQuery = tintucthongbaoQuery.OrderBy(tt => tt.NoiDung);
                    break;
                case "ngaytao":
                    tintucthongbaoQuery = tintucthongbaoQuery.OrderBy(tt => tt.NgayTao);
                    break;
                default:
                    tintucthongbaoQuery = tintucthongbaoQuery.OrderBy(tt => tt.NgayTao);
                    break;
            }

            int totalRecords = tintucthongbaoQuery.Count();
            int totalPages = (int)Math.Ceiling((double)totalRecords / pageSize);
            int recordsToSkip = (page - 1) * pageSize;

            var dstt = tintucthongbaoQuery.Skip(recordsToSkip).Take(pageSize).ToList();

            ViewBag.Search = search;
            ViewBag.SortOrder = sortOrder;
            ViewBag.Page = page;
            ViewBag.TotalPages = totalPages;

            return View(dstt);
        }

        public ActionResult TinTucThongBaoAdd()
        {
            return View();
        }
        [HttpPost]
        public ActionResult TinTucThongBaoAdd(TinTucThongBao tt, HttpPostedFileBase imageFile)
        {
            if (ModelState.IsValid)
            {
                if (string.IsNullOrEmpty(tt.TieuDe)
                    && string.IsNullOrEmpty(tt.Anh)
                    && string.IsNullOrEmpty(tt.NoiDung)
                    && string.IsNullOrEmpty(tt.LoaiTin))
                {
                    ModelState.AddModelError("", "Vui lòng nhập đầy đủ thông tin của giảng viên!!!");
                    return View();
                }

                string filename = "noimage.jpg";
                if (imageFile != null && imageFile.ContentLength > 0)
                {
                    var allowedExtensions = new[] { ".jpg", ".png" };
                    var fileEx = Path.GetExtension(imageFile.FileName).ToLower();
                    if (!allowedExtensions.Contains(fileEx) || imageFile.ContentLength > 2000000)
                    {
                        ModelState.AddModelError("Anh", "Chỉ chấp nhận hình ảnh JPG hoặc PNG và không lớn hơn 2MB.");
                        return View();
                    }

                    filename = imageFile.FileName;
                    var path = Path.Combine(Server.MapPath("~/images"), filename);
                    imageFile.SaveAs(path);
                }

                DateTime truncatedToSecond = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, DateTime.Now.Hour, DateTime.Now.Minute, DateTime.Now.Second);

                try
                {
                    TinTucThongBao tintuc = new TinTucThongBao
                    {
                        Anh = filename,
                        TieuDe = tt.TieuDe,
                        NoiDung = tt.NoiDung,
                        LoaiTin = tt.LoaiTin,
                        NgayTao = truncatedToSecond,
                        TrangThai = true
                    };

                    db.TinTucThongBao.Add(tintuc);
                    db.SaveChanges();
                }
                catch(Exception ex)
                {
                    TempData["ErrorMessage"] = "Có lỗi xảy ra khi đăng bài: " + ex;
                    return RedirectToAction("DanhSachTinTucThongBao");
                }

                TempData["SuccessMessage"] = "Đã đăng bài thành công";
                return RedirectToAction("DanhSachTinTucThongBao");
            }
            else
            {
                TempData["ErrorMessage"] = "Có lỗi xảy ra khi đăng bài!!! Hãy thử lại sau";
                return RedirectToAction("DanhSachTinTucThongBao");
            }
        }

        public ActionResult TinTucThongBaoEdit(int id)
        {
            TinTucThongBao tt = db.TinTucThongBao.FirstOrDefault(t => t.ID == id);
            if (tt == null)
            {
                return HttpNotFound("Không tìm thấy học viên.");
            }
            return View(tt);
        }
        [HttpPost]
        public ActionResult TinTucThongBaoEdit(TinTucThongBao tintuc, HttpPostedFileBase imageFile)
        {
            try
            {
                TinTucThongBao tt = db.TinTucThongBao.FirstOrDefault(t => t.ID == tintuc.ID);
                if (tt == null)
                {
                    TempData["ErrorMessage"] = "Không tìm thấy bài đăng!!!";
                    return RedirectToAction("TinTucThongBaoEdit", new { tintuc.ID });
                }

                tt.TieuDe = tintuc.TieuDe;
                tt.NoiDung = tintuc.NoiDung;
                tt.LoaiTin = tintuc.LoaiTin;
                tt.TrangThai = tintuc.TrangThai;

                if (imageFile != null && imageFile.ContentLength > 0)
                {
                    var allowedExtensions = new[] { ".jpg", ".png" };
                    var fileEx = Path.GetExtension(imageFile.FileName).ToLower();
                    if (!allowedExtensions.Contains(fileEx) || imageFile.ContentLength > 2000000)
                    {
                        ModelState.AddModelError("Anh", "Chỉ chấp nhận hình ảnh JPG hoặc PNG và không lớn hơn 2MB.");
                        return View();
                    }

                    string fileName = tt.ID + fileEx;
                    var path = Path.Combine(Server.MapPath("~/images"), fileName);
                    imageFile.SaveAs(path);
                    tt.Anh = fileName;
                }

                db.SaveChanges();
                TempData["SuccessMessage"] = "Đã sửa bài đăng thành công";
            }
            catch(Exception ex)
            {
                TempData["ErrorMessage"] = "Có lỗi xảy ra khi sửa bài đăng: " + ex;
            }
            return RedirectToAction("TinTucThongBaoEdit", new { tintuc.ID });
        }

        public ActionResult TinTucThongBaoDelete(int id)
        {
            var tintuc = db.TinTucThongBao.FirstOrDefault(t => t.ID == id);
            if(tintuc == null)
            {
                TempData["ErrorMessage"] = "Bài đăng không tồn tại";
                return RedirectToAction("DanhSachTinTucThongBao");
            }
            return View(tintuc);
        }
        [HttpPost]
        public ActionResult TinTucThongBaoDelete(int id, TinTucThongBao tintuc)
        {
            try
            {
                tintuc = db.TinTucThongBao.Where(t => t.ID == id).FirstOrDefault();
                db.TinTucThongBao.Remove(tintuc);
                db.SaveChanges();
                TempData["SuccessMessage"] = "Đã xóa bài đăng thành công";
            }   
            catch(Exception ex)
            {
                TempData["ErrorMessage"] = "Có lỗi xảy ra khi xóa bài đăng: " + ex;
            }
            return RedirectToAction("DanhSachTinTucThongBao");
        }    
    }
}

DoAnChuyenNganh_HeThongTrungTamTinHoc/Areas/Admin/Views/AdminTinTucThongBao/DanhSachTinTucThongBao.cshtml
@model List<DoAnChuyenNganh_HeThongTrungTamTinHoc.Models.TinTucThongBao>
@{
    ViewBag.Title = "DanhSachTinTucThongBao";
    Layout = "~/Areas/Admin/Views/Shared/Layout_Admin.cshtml";
}

<style>
    .custom-table {
        background-color: #ffffff;
        border-radius: 10px;
        overflow: hidden;
        box-shadow: 0px 4px 12px rgba(0, 0, 0, 0.1);
    }

    .custom-table thead {
        background-color: #007bff;
        color: white;
    }

    .custom-table thead th {
        font-weight: bold;
        text-transform: uppercase;
        padding: 12px 15px;
    }

    .custom-table tbody tr:hover {
        background-color: #f1f5f9;
    }

    .custom-table tbody td {
        padding: 12px 15px;
        vertical-align: middle;
    }

    .table-responsive {
        padding: 15px;
        background-color: #f8f9fa;
        border-radius: 10px;
    }
</style>

@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        @TempData["SuccessMessage"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        @TempData["ErrorMessage"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}


<a class="btn btn-outline-primary mt-3" style="width: 180px;" href="@Url.Action("Index", "Admin")">Quay lại</a>
<br />
<div class="d-flex gap-2">
    <a class="btn btn-outline-primary mt-2 mb-2" style="width: 180px;" href="@Url.Action("TinTucThongBaoAdd", "AdminTinTucThongBao")">Đăng bài</a>
</div>


<form class="d-flex mb-3 mt-2" action="@Url.Action("DanhSachTinTucThongBao", "AdminTinTucThongBao")">
    <input class="form-control me-2" id="search" name="search" value="@ViewBag.Search" type="search" placeholder="Tìm kiếm lớp học" aria-label="Search" style="max-width: 400px;">
    <button class="btn btn-outline-primary ms-2" type="submit">Tìm kiếm</button>
    <a class="btn btn-danger ms-2" href="@Url.Action("DanhSachTinTucThongBao", "AdminTinTucThongBao")">Hủy</a>
</form>

<div class="d-flex justify-content-between mb-3">
    <form class="d-inline">
        <label for="sortOrder" class="me-2 fw-bold">Sắp xếp:</label>
        <select name="sortOrder" id="sortOrder" class="form-select d-inline w-auto" onchange="this.form.submit()">
            <option value="tieude" @(ViewBag.SortOrder == "tieude" ? "selected" : "")>Tiêu đề</option>
            <option value="noidung" @(ViewBag.SortOrder == "noidung" ? "selected" : "")>Nội dung</option>
            <option value="ngaytao" @(ViewBag.SortOrder == "ngaytao" ? "selected" : "")>Ngày tạo</option>
        </select>
    </form>
</div>

<div class="container mt-5">
    <h2 class="mb-4 text-center" style="color: #0066b3">Danh sách Tin tức & Thông báo</h2>
    <div class="table-responsive">
        <table class="table custom-table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Ảnh</th>
                    <th>Tiêu đề</th>
                    <th>Nội dung</th>
                    <th>Loại tin</th>
                    <th>Ngày tạo</th>
                    <th>Trạng thái</th>
                    <th>Hành động</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.ID</td>
                        <td>
                            @{ var imagePath = Server.MapPath($"~/images/{item.Anh}");
                                if (System.IO.File.Exists(imagePath) && item.Anh != null)
                                {
                                    <img src="~/images/@item.Anh" width="150px" />
                                }
                                else
                                {
                                    <img src="~/images/noimage.jpg" width="150px" />
                                }
                            }
                        </td>
                        <td>@item.TieuDe</td>
                        <td>@item.NoiDung</td>
                        <td>@item.LoaiTin</td>
                        <td>@item.NgayTao</td>
                        <td>@item.TrangThai</td>
                        <td>
                            <div class="d-flex gap-2">
                                <a href="@Url.Action("TinTucThongBaoEdit", "AdminTinTucThongBao", new { id = item.ID })" style="text-decoration: none;" class="btn btn-primary btn-sm">Sửa</a>
                                <a href="@Url.Action("TinTucThongBaoDelete", "AdminTinTucThongBao", new { id = item.ID })" style="text-decoration: none;" class="btn btn-danger btn-sm">Xóa</a>
                            </div>
                        </td>
                    </tr>

                }
            </tbody>
        </table>
    </div>
</div>

<div class="container-fluid d-flex justify-content-center">
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            @{
                int trangtruoc = ViewBag.Page - 1;
                int trangsau = ViewBag.Page + 1;
                int totalPages = ViewBag.totalPages;
                int startPage = Math.Max(ViewBag.Page - 2, 1);
                int endPage = Math.Min(ViewBag.Page + 2, totalPages);
            }

            <li class="page-item @(ViewBag.Page == 1 ? "disabled" : "")">
                <a class="page-link" href="?page=@trangtruoc&search=@ViewBag.Search&sortOrder=@ViewBag.SortOrder" tabindex="-1"><</a>
            </li>

            @if (startPage > 1)
            {
                <li class="page-item"><a class="page-link" href="?page=1&search=@ViewBag.Search&sortOrder=@ViewBag.SortOrder">1</a></li>
                if (startPage > 2)
                {
                    <li class="page-item disabled"><span class="page-link">...</span></li>
                }
            }

            @for (int i = startPage; i <= endPage; i++)
            {
                <li class="page-item @(i == ViewBag.Page ? "active" : "")">
                    <a class="page-link" href="?page=@i&search=@ViewBag.Search&sortOrder=@ViewBag.SortOrder">@i</a>
                </li>
            }

            @if (endPage < totalPages)
            {
                if (endPage < totalPages - 1)
                {
                    <li class="page-item disabled"><span class="page-link">...</span></li>
                }
                <li class="page-item"><a class="page-link" href="?page=@totalPages&search=@ViewBag.Search&sortOrder=@ViewBag.SortOrder">@totalPages</a></li>
            }

            <li class="page-item @(ViewBag.Page == totalPages ? "disabled" : "")">
                <a class="page-link" href="?page=@trangsau&search=@ViewBag.Search&sortOrder=@ViewBag.SortOrder">></a>
            </li>
        </ul>
    </nav>
</div>

DoAnChuyenNganh_HeThongTrungTamTinHoc/Areas/Admin/Views/AdminTinTucThongBao/TinTucThongBaoAdd.cshtml
@model DoAnChuyenNganh_HeThongTrungTamTinHoc.Models.TinTucThongBao
@{
    ViewBag.Title = "Đăng bài";
    Layout = "~/Areas/Admin/Views/Shared/Layout_Admin.cshtml";
}

<div class="card mb-3 mx-auto mt-3" style="max-width: 800px;">
    <div class="row g-0 mt-1 mb-0">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card-body p-0 text-dark">
                <h2 style="color: #0066b3">@ViewBag.Title</h2>
            </div>
        </div>
    </div>
    <div class="row g-0 mt-1">
        <div class="col-md-12">
            <div class="card-body text-dark p-0">
                @using (Html.BeginForm("TinTucThongBaoAdd", "AdminTinTucThongBao", new { area = "Admin" }, FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    <div class="row my-2">
                        <div class="col-3"></div>
                        <div class="col-6">
                            @Html.LabelFor(model => model.Anh, "Ảnh bài đăng")
                            <input type="file" name="imageFile" id="imageFile" class="form-control" />
                            @Html.ValidationMessageFor(model => model.Anh, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="row my-2">
                        <div class="col-3"></div>
                        <div class="col-6">
                            @Html.LabelFor(model => model.TieuDe, "Tiêu đề")
                            @Html.TextBoxFor(model => model.TieuDe, new { placeholder = "Tiêu đề", @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.TieuDe, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="row my-2">
                        <div class="col-3"></div>
                        <div class="col-6">
                            @Html.LabelFor(model => model.NoiDung, "Nội dung")
                            @Html.TextAreaFor(model => model.NoiDung, new { placeholder = "Nội dung", @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.NoiDung, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="row my-2">
                        <div class="col-3"></div>
                        <div class="col-6">
                            @Html.LabelFor(model => model.LoaiTin, "Loại tin")
                            @Html.DropDownListFor(model => model.LoaiTin, new List<SelectListItem>()
                               {
                                    new SelectListItem {Text = "Tin tức",Value = "Tin tức"},
                                    new SelectListItem {Text = "Thông báo",Value = "Thông báo"},
                               }, "Chọn loại tin", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.LoaiTin, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="row my-2 mt-3 mb-3">
                        <div class="col-3"></div>
                        <div class="col-6">
                            <button type="submit" class="btn btn-primary">Đăng bài</button> &nbsp;
                            <a href="/Admin/AdminTinTucThongBao/DanhSachTinTucThongBao" class="btn btn-danger">Quay lại</a>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

DoAnChuyenNganh_HeThongTrungTamTinHoc/Areas/Admin/Views/AdminTinTucThongBao/TinTucThongBaoDelete.cshtml
@model DoAnChuyenNganh_HeThongTrungTamTinHoc.Models.TinTucThongBao
@{
    ViewBag.Title = "TinTucThongBaoDelete";
    Layout = "~/Areas/Admin/Views/Shared/Layout_Admin.cshtml";
}

<h3>Bạn có chắc chắn muốn xóa bài đăng này không?</h3>
<div class="card mb-3 mx-auto mt-3" style="max-width: 800px;">
    <form class="p-4 mt-0" style="max-width: 100%" action="/Admin/AdminTinTucThongBao/TinTucThongBaoDelete/@Model.ID" method="post">
        <input type="hidden" name="Id" value="@Model.ID" />
        <hr />
        <dl class="dl-horizontal">
            <dt>
                Ảnh bài đăng
            </dt>
            <dd>
                @if (!string.IsNullOrEmpty(Model.Anh))
                {
                    {
                        var imagePath = Server.MapPath($"~/images/{Model.Anh}");
                        if (System.IO.File.Exists(imagePath) && Model.Anh != null)
                        {
                            <img src="~/images/@Model.Anh" width="150px" />
                        }
                        else
                        {
                            <img src="~/images/noimage.jpg" width="150px" />
                        }
                    }
                }
            </dd>
            &nbsp;
            &nbsp;

            <dt>
                Tiêu đề
            </dt>
            <dd>
                @Html.DisplayFor(model => model.TieuDe)
            </dd>
            &nbsp;
            &nbsp;
            <dt>
                Nội dung
            </dt>
            <dd>
                @Html.DisplayFor(model => model.NoiDung)
            </dd>
            &nbsp;
            &nbsp;

            <dt>
                Ngày đăng
            </dt>
            <dd>
                @Html.DisplayFor(model => model.NgayTao)
            </dd>
            &nbsp;
            &nbsp;
            <dt>
                Loại tin
            </dt>
            <dd>
                @Html.DisplayFor(model => model.LoaiTin)
            </dd>
            &nbsp;
            &nbsp;
            <dt>
                Trạng thái
            </dt>
            <dd>
                @Html.DisplayFor(model => model.TrangThai)
            </dd>
            &nbsp;
            &nbsp;
        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Xóa" class="btn btn-danger" />
                <a class="btn btn-secondary ms-2" href="@Url.Action("DanhSachTinTucThongBao", "AdminTinTucThongBao")">Quay lại</a>
            </div>
        }
    </form>
</div>

DoAnChuyenNganh_HeThongTrungTamTinHoc/Areas/Admin/Views/AdminTinTucThongBao/TinTucThongBaoEdit.cshtml
@model DoAnChuyenNganh_HeThongTrungTamTinHoc.Models.TinTucThongBao
@{
    ViewBag.Title = "TinTucThongBaoEdit";
    Layout = "~/Areas/Admin/Views/Shared/Layout_Admin.cshtml";
}

@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        @TempData["SuccessMessage"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        @TempData["ErrorMessage"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

<div class="card mb-3 mx-auto mt-3" style="max-width: 800px;">
    <div class="row g-0 mt-1 mb-0">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card-body p-0 text-dark">
                <h2 style="color: #0066b3">Chỉnh sửa thông tin bài đăng</h2>
            </div>
        </div>
    </div>

    <div class="row g-0 mt-1">
        <div class="col-md-12">
            <div class="card-body text-dark p-0">
                @using (Html.BeginForm("TinTucThongBaoEdit", "AdminTinTucThongBao", new { area = "Admin" }, FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.ID)


                    <div class="row my-2">
                        <div class="col-3"></div>
                        <div class="col-6">
                            @Html.LabelFor(model => model.Anh, "Ảnh bài đăng")
                            <input type="file" name="imageFile" id="imageFile" class="form-control" />
                            <p>Ảnh hiện tại:</p>
                            @{
                                var imagePath = Server.MapPath($"~/images/{Model.Anh}");
                                if (System.IO.File.Exists(imagePath) && Model.Anh != null)
                                {
                                    <img src="~/images/@Model.Anh" width="150px"/>
                                }
                                else
                                {
                                    <img src="~/images/noimage.jpg" width="150px"/>
                                }
                            }
                            @Html.ValidationMessageFor(model => model.Anh, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="row my-2">
                        <div class="col-3"></div>
                        <div class="col-6">
                            @Html.LabelFor(model => model.TieuDe, "Tiêu đề")
                            @Html.EditorFor(model => model.TieuDe, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TieuDe, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="row my-2">
                        <div class="col-3"></div>
                        <div class="col-6">
                            @Html.LabelFor(model => model.NoiDung, "Nội dung")
                            @Html.TextBoxFor(model => model.NoiDung, new { placeholder = "Ngày sinh", @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.NoiDung, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="row my-2">
                        <div class="col-3"></div>
                        <div class="col-6">
                            @Html.LabelFor(model => model.LoaiTin, "Loại tin")
                            @Html.DropDownListFor(model => model.LoaiTin, new List<SelectListItem>()
                               {
                                    new SelectListItem {Text = "Tin tức", Value = "Tin tức", Selected = Model.LoaiTin == "Tin tức"},
                                    new SelectListItem {Text = "Thông báo", Value = "Thông báo", Selected = Model.LoaiTin == "Thông báo"},
                               }, "Chọn loại tin", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.LoaiTin, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="row my-2">
                        <div class="col-3"></div>
                        <div class="col-6">
                            @Html.LabelFor(model => model.TrangThai, "Trạng thái")
                            @Html.DropDownListFor(model => model.TrangThai, new List<SelectListItem>()
                               {
                                    new SelectListItem {Text = "Hiện", Value = "true", Selected = Model.TrangThai == true},
                                    new SelectListItem {Text = "Ẩn", Value = "false", Selected = Model.TrangThai == false},
                               }, "Chọn trạng thái", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.TrangThai, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="row my-2 mt-3 mb-3">
                        <div class="col-3"></div>
                        <div class="col-6">
                            <button type="submit" class="btn btn-primary">Lưu thay đổi</button> &nbsp;
                            <a href="/Admin/AdminTinTucThongBao/DanhSachTinTucThongBao" class="btn btn-danger">Quay lại</a>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>